const EVENTS = Object.freeze({
  THREAT_DETECTED: 'THREAT_DETECTED',
  LOG_BATCH_PROCESSED: 'LOG_BATCH_PROCESSED',
  INTEL_ENRICHED: 'INTEL_ENRICHED',
  IOC_UPDATED: 'IOC_UPDATED',
  INCIDENT_TRIAGED: 'INCIDENT_TRIAGED',
  THREAT_LEVEL_CHANGED: 'THREAT_LEVEL_CHANGED',
  RESPONSE_INITIATED: 'RESPONSE_INITIATED',
  RESPONSE_EXECUTED: 'RESPONSE_EXECUTED',
  RESPONSE_ROLLED_BACK: 'RESPONSE_ROLLED_BACK',
  HITL_REQUIRED: 'HITL_REQUIRED',
  HITL_APPROVED: 'HITL_APPROVED',
  HITL_REJECTED: 'HITL_REJECTED',
  HITL_TIMEOUT: 'HITL_TIMEOUT',
  EVIDENCE_COLLECTED: 'EVIDENCE_COLLECTED',
  FORENSICS_COMPLETE: 'FORENSICS_COMPLETE',
  RED_TEAM_SIMULATION_STARTED: 'RED_TEAM_SIMULATION_STARTED',
  RED_TEAM_SIMULATION_COMPLETE: 'RED_TEAM_SIMULATION_COMPLETE',
  DETECTION_RULES_UPDATED: 'DETECTION_RULES_UPDATED',
  HONEYPOT_TRIGGERED: 'HONEYPOT_TRIGGERED',
  DECEPTION_DEPLOYED: 'DECEPTION_DEPLOYED',
  ATTACKER_PROFILED: 'ATTACKER_PROFILED',
  AUDIT_ENTRY_CREATED: 'AUDIT_ENTRY_CREATED',
  COMPLIANCE_REPORT_GENERATED: 'COMPLIANCE_REPORT_GENERATED',
  TASK_ROUTED: 'TASK_ROUTED',
  CONFLICT_RESOLVED: 'CONFLICT_RESOLVED',
  GLOBAL_THREAT_LEVEL_SET: 'GLOBAL_THREAT_LEVEL_SET',
  AGENT_HEALTH_CHECK: 'AGENT_HEALTH_CHECK',
  AGENT_STARTED: 'AGENT_STARTED',
  AGENT_ERROR: 'AGENT_ERROR',
  SYSTEM_READY: 'SYSTEM_READY',
  ML_PRESCORED: 'ML_PRESCORED',
  LOG_BATCH_RECEIVED: 'LOG_BATCH_RECEIVED'
});

module.exports = {
  EVENTS
};